### ISSUE TITLE
Crashes my login server

### ISSUE THREAD

**Issue by GabIsAwesome** [brosquinha/houdini-bot-plugin#2]
When using this bot plugin, it crashes my login server, making the game pratically unplayable

```
wand-houdini_login-1      | Traceback (most recent call last):
wand-houdini_login-1      |   File "/usr/src/houdini/bootstrap.py", line 141, in <module>
wand-houdini_login-1      |     asyncio.run(factory_instance.start())
wand-houdini_login-1      |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
wand-houdini_login-1      |     return runner.run(main)
wand-houdini_login-1      |            ^^^^^^^^^^^^^^^^
wand-houdini_login-1      |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
wand-houdini_login-1      |     return self._loop.run_until_complete(task)
wand-houdini_login-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wand-houdini_login-1      |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
wand-houdini_login-1      |   File "/usr/src/houdini/houdini/houdini.py", line 172, in start
wand-houdini_login-1      |     await self.plugins.setup(houdini.plugins)
wand-houdini_login-1      |   File "/usr/src/houdini/houdini/plugins/__init__.py", line 58, in setup
wand-houdini_login-1      |     await self.load(plugin_package)
wand-houdini_login-1      |   File "/usr/src/houdini/houdini/plugins/__init__.py", line 61, in load
wand-houdini_login-1      |     plugin_class, plugin_type = inspect.getmembers(module, is_plugin).pop()
wand-houdini_login-1      |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wand-houdini_login-1      | IndexError: pop from empty list
```

**Comment by GabIsAwesome** [comment]
I found out the problem was on my side, sorry for the inconvenience
